version: 2.1

jobs:
  build:           
    docker:         
      - image: cimg/base:current
    working_directory: ~/app
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Install dependencies
          command: echo "Build udagram frontend"
      - run:
          name: Build and push Docker image
          command: |
            echo "check"
            node -v && npm -v
            echo "Inside the Build and push Docker image step"
            docker-compose -f docker-compose-build.yaml build --parallel
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker-compose -f docker-compose-build.yaml push
