version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- check -----------"
            node 0-v && docker -v && docker-compose -v

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]


