version: 2.1

jobs:
  lint-app:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
  build-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: Build docker container for each microservices
          command: |
            echo "--------- check -----------"
            node -v && docker -v && docker-compose -v
            
            echo "--------- Installing dependencies-----------"
            sudo curl -LO https://nodejs.org/dist/v13.14.0/node-v13.14.0-linux-x64.tar.xz
            sudo tar -xvf node-v13.14.0-linux-x64.tar.xz
            sudo cp -r node-v13.14.0-linux-x64/{bin,include,lib,share} /usr/
            node --version => v13.14.0
            sudo apt install nodejs
            echo "--------- check -----------"
            node -v && docker -v && docker-compose -v
            

workflows:
  default:
    jobs:
      - lint-app
      - build-docker:
          requires: [lint-app]


